# 1 Find a stationary point

In [ ]:
import numpy as np

Af = np.array([[5, 3, 5], 
               [3, 4, 0], 
               [5, 0, -4]])
bf = np.array([-39, 42, -101])

def f(x):
    return x.T @ Af @ x + bf @ x

def grad_f(x):
    return 2 * Af @ x + bf

def grad_h1(x=None):
    return np.array([-2, 3, -9])

def grad_h2(x=None):
    return np.array([-5, -10, 1])

def hess_f(x):
    return 2 * Af

In [ ]:
Ainv_b1 = np.linalg.solve(Af, grad_h1())
Ainv_b2 = np.linalg.solve(Af, grad_h2())

A = np.array([[grad_h1() @ Ainv_b1, grad_h1() @ Ainv_b2], 
              [grad_h2() @ Ainv_b1, grad_h2() @ Ainv_b2]])

# print(A)

Ainv_bf = np.linalg.solve(Af, bf) 

b = 2 * np.array([-57, 56]) + np.array([grad_h1() @ Ainv_bf, 
                                         grad_h2() @ Ainv_bf])

lambdas = np.linalg.solve(A, b)

print(f'lambdas: {lambdas}')

lambdas: [ 2. -1.]


In [ ]:
x = - 0.5 * (Ainv_bf + lambdas[0] * Ainv_b1 + lambdas[1] * Ainv_b2)

print(f'Solution: {x}')

Solution: [ 12.86111111 -16.89583333   1.07638889]


In [ ]:
5 - 47 / 87 * 6 + 10 * (5 - 10 * 47 / 87) + 4 * (47 / 87) ** 2 - 4 * (5 - 10 * 47 / 87) ** 2

-1.7443519619500631

function is concave, hence the point corresponds to the maximum of the function

# 2 Check whether xs are stationary points.

In [ ]:
import numpy as np

def h1(x):
    res = 14 * x[0] ** 2 + 6 * x[0] * x[1] + 8 * x[0] * x[2] + 232 * x[0]
    res += 14 * x[1] ** 2 - 10 * x[1] * x[2] - 734 * x[1]
    res += 12 * x[2] ** 2 - 154 * x[2] - 120.
    return res

def g1(x):
    return -257 * x[0] + 377.5 * x[1] + 216 * x[2] - 213.5

def g2(x):
    return 70 * x[0] + 317 * x[1] + 215 * x[2] - 1457


x1 = np.array([4., 1., 4.])
x2 = np.array([7.641261, 4.692335, -2.629574])
x3 = np.array([3.931046, 10.638642, -12.927354])

In [ ]:
def primal_feasibility(x):
    print(f'primal_feasibility for {x}')
    print(f'h1: {h1(x)}, {h1(x) == 0}')
    print(f'g1: {g1(x)}, {g1(x) <= 0}')
    print(f'g2: {g2(x)}, {g2(x) <= 0}')


primal_feasibility(x1)
primal_feasibility(x2)
primal_feasibility(x3)

primal_feasibility for [4. 1. 4.]
h1: 0.0, True
g1: 0.0, True
g2: 0.0, True
primal_feasibility for [ 7.641261  4.692335 -2.629574]
h1: -0.00027529244641755213, False
g1: -973.9355985000001, True
g2: 5.499999997482519e-05, False
primal_feasibility for [  3.931046  10.638642 -12.927354]
h1: -2.233668874396244e-05, False
g1: 6.900000062159961e-05, False
g2: -588.7583759999993, True


The second point is not even feasible

The first point is feasible + for $g_{1, 2}(x) = 0$ it follows that $\mu_{1, 2} \geq 0$

In [ ]:
Ah = np.array([[14, 3, 4], 
               [3, 14, -5], 
               [4, -5, 12]])

bh = np.array([232., -734., -154.])

def grad_f(x):
    return np.array([4 * 4 * x[0] ** 3 + 2 * 2 * x[0] * x[1] ** 2 - 4 * 2 * x[0] * x[2] ** 2, 
                     2 * 2 * x[0] ** 2 * x[1] - 4 * x[1] ** 3 - 6 * 2 * x[1] * x[2] ** 2, 
                     -4 * 2 * x[0] ** 2 * x[2] - 6 * 2 * x[1] ** 2 * x[2] - 4 * 4 * x[2] ** 3])

def grad_h1(x):
    return 2 * Ah @ x + bh

def grad_g1(x):
    return np.array([-257., 377.5, 216.])

def grad_g2(x):
    return np.array([70., 317., 215.])

In [ ]:
print(f'grad_f: {grad_f(x1)}')
print(f'grad_h1: {grad_h1(x1)}')

grad_f: [  528.  -132. -1584.]
grad_h1: [ 382. -722.  -36.]


In [ ]:
np.linalg.solve(np.hstack([grad_h1(x1).reshape(-1, 1), 
                           grad_g1(x1).reshape(-1, 1), 
                           grad_g2(x1).reshape(-1, 1)]), 
                -grad_f(x1))

array([4., 8., 0.])

From the last two components which are responsible for $\mu_{1, 2}$ we can conclude that it is stationary point of the problem

The third point is feasible up to the machine precision: $\mu_1 \geq 0$, $\mu_2 = 0$

In [ ]:
print(f'grad_f: {grad_f(x3)}')
print(f'grad_h1: {grad_h1(x3)}')

grad_f: [ -2503.91542256 -25493.46400926  53721.65079038]
grad_h1: [ 302.482308 -283.258208 -539.194548]


In [ ]:
np.linalg.solve(np.hstack([grad_h1(x3).reshape(-1, 1), 
                           grad_g1(x3).reshape(-1, 1), 
                           grad_g2(x3).reshape(-1, 1)]), 
                -grad_f(x1))

array([-3.99986531e+00, -2.65286559e+00,  1.45765883e-03])

From the last two components which are responsible for $\mu_{1, 2}$ we can conclude that daul feasibility doesnt hold

# 3 Use SQP-Algorithm to find a solution.

In [ ]:
import numpy as np
from tqdm.notebook import tqdm


Af = np.array([[22., 12.], 
               [12., 8.]])

bf = np.array([6., -16.])


Ah = np.array([[13., 2.], [2., 9]])


def f(x):
    return x.T @ Af @ x + bf @ x


def h(x):
    return (x.T @ Ah @ x - 9.).reshape(1)


def grad_f(x):
    return 2 * Af @ x + bf


def hess_f(x):
    return 2 * Af


def jac_h(x):
    return 2 * (Ah @ x).reshape(1, -1)


def hess_h(x):
    return 2 * Ah


def SQP(grad, hs, jac, hesses, eps, x0, lambda0, max_iter=10**4):
    xk = x0.copy()
    lambdak = lambda0.copy()
    
    for k in tqdm(range(max_iter)):
        gk = grad(xk)
        Ak = jac(xk)
        Dk = hesses[0](xk)
        
        for i in range(len(lambdak)):
            Dk += lambdak[i] * hesses[i + 1](xk)
        
        rk = hs(xk)
        A = np.block([[Dk, Ak.T], 
                      [Ak, np.eye(Ak.shape[0])]])
        # print(gk, rk)
        b = -np.hstack([gk, rk])
        pk = np.linalg.solve(A, b)
        
        uk = pk[-len(lambdak):]
        pk = pk[:len(xk)]
        
        if np.linalg.norm(pk) <= eps:
            break
        else:
            xk += pk
            lambdak = uk
        
    return xk, lambdak



In [ ]:
x0 = np.array([3., 3.]) 
lambda0 = np.array([3.])
eps = 1e-3

SQP(grad_f, h, jac_h, [hess_f, hess_h], eps=eps, x0=x0, lambda0=lambda0)

  0%|          | 0/10000 [00:00<?, ?it/s]

(array([-0.45172923,  0.88514492]), array([0.8969542]))

In [ ]:
x_res = np.array([-0.45172923,  0.88514492])
f(x_res)

-15.711837321185183

# 2 Find a stationary point of function

In [ ]:
import numpy as np
from scipy.optimize import line_search


def PolakRibiere(f, grad_f, x0, eps, max_iter=10**4):
    xk = x0.copy()
    gk = grad_f(x0)
    dk = -gk.copy()
    
    for k in tqdm(range(max_iter)):
        # print(np.linalg.norm(gk))
        if np.linalg.norm(gk) < eps:
            break

        tau = line_search(f, grad_f, xk, dk)[0]
        tau = 1e-4 if tau is None else tau
        # print(xk)
        # print(dk)
        # print(tau)
        xk += tau * dk
        betak = np.maximum(0, gk @ (grad_f(xk) - gk) / gk.T @ gk)
        gk = grad_f(xk)
        dk = -gk + betak * dk

    return xk     

def f(x):
    return sum((x[i] ** 2 + x[i + 1] - 11) ** 2 + (x[i] + x[i + 1] ** 2 - 7) ** 2 for i in range(0, len(x), 2))

def grad_f(x):
    res = [2 * (x[0] ** 2 + x[1] - 11) * 2 * x[0] + 2 * (x[0] + x[1] ** 2 - 7)] 
    
    for i in range(1, len(x) - 1):
        tmp = 2 * (x[i] ** 2 + x[i + 1] - 11) * 2 * x[i] + 2 * (x[i] + x[i + 1] ** 2 - 7)
        tmp += 2 * (x[i - 1] ** 2 + x[i] - 11) + 2 * (x[i - 1] + x[i] ** 2 - 7) * 2 * x[i] ** 2
        res += [tmp]

    res += [2 * (x[-2] ** 2 + x[-1] - 11) + 2 * (x[-2] + x[-1] ** 2 - 7) * 2 * x[-1] ** 2]
    return np.hstack(res)

x0 = np.ones(10)
eps = 1e-3


PolakRibiere(f, grad_f, x0, eps, max_iter=10**4)

  0%|          | 0/10000 [00:00<?, ?it/s]

/usr/local/lib/python3.7/dist-packages/scipy/optimize/linesearch.py:314: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)


array([2.90895969, 2.31779376, 2.43593756, 2.41363586, 2.4178948 ,
       2.41704899, 2.41752285, 2.41462809, 2.44023788, 2.20286   ])

In [ ]:
x_res = np.array([2.90895969, 2.31779376, 2.43593756, 2.41363586, 2.4178948 ,
       2.41704899, 2.41752285, 2.41462809, 2.44023788, 2.20286   ])

f(x_res)

36.62993284112714

# 3 Find a minimum point of convex function

In [ ]:
import numpy as np

def f(x):
    res = x[2] ** 2 + 10 * (x[0] + x[1] - 1) ** 2 - 160
    res += 3 * (1 - x[0]) ** 2 + 3 * (2 - x[1]) ** 2 - 12 * x[2]
    res += 4 * (2 - x[0]) ** 4 + 4 * (1 - x[1]) ** 4
    res += 5 * (4 - x[0]) ** 4 + 5 * (4 - x[1]) ** 4
    return res

def grad_f(x):
    return np.array([10 * (x[0] + x[1] - 1) - 3 * 4 * (1 - x[0]) ** 3 - 4 * 4 * (2 - x[0]) ** 3 - 5 * 4 * (4 - x[0]) ** 3,
                     10 * (x[0] + x[1] - 1) - 3 * 4 * (2 - x[1]) ** 3 - 4 * 4 * (1 - x[1]) ** 3 - 5 * 4 * (4 - x[1]) ** 3,
                     2 * x[2] - 12])

def hess_f(x):
    return np.array([[10 + 3 * 4 * 3 * (1 - x[0]) ** 2 + 4 * 4 * 3 * (2 - x[0]) ** 2 + 5 * 4 * 3 * (4 - x[0]) ** 2, 10, 0], 
                     [10, 10 + 3 * 4 * 3 * (2 - x[1]) ** 2 + 4 * 4 * 3 * (1 - x[1]) ** 2 + 5 * 4 * 4 * (4 - x[1]) ** 2, 0], 
                     [0, 0, 2]])


def Newton(f, grad, hess, x0, eps, max_iter=10**4):
    xk = x0.copy()
    # print(xk)
    # print(gk)
    for k in tqdm(range(max_iter)):
        # print(np.linalg.norm(gk))
        gk = grad_f(xk)
        if np.linalg.norm(gk) < eps:
            break
        W = hess(xk)
        l = np.linalg.eigvalsh(W)[0]

        if l <= 0:
            print(1)
            W += -l * np.eye(W.shape[0]) + 1e-3

        dk = np.linalg.solve(W, -gk)
        tau = None
        tau = 1e-2 if tau is None else tau
        xk += tau * dk
    
    return xk


x0 = np.random.randn(3)
eps = 1e-3

Newton(f, grad_f, hess_f, x0, eps, max_iter=10**4)

  0%|          | 0/10000 [00:00<?, ?it/s]

array([2.44157502, 2.39556461, 5.9999999 ])

In [ ]:
x_res = np.array([2.44157502, 2.39556461, 5.9999999 ])
f(x_res)

35.89040721419608